<?

  $title = "Medical Waste Disposal for Hospitals &amp; Healthcare Systems";
  $desc = "With GICMD's convenient services, we can help make it easier  for you, your medical staff, and other hospital employees.";

?>
<?php include 'components/header.php'; ?>

<div class="shadow mainImage center mgnT14" style="background-image: url(img/about.jpg);"></div>

<br>

<div class="clear"></div>

<div class="contentBox mgnBI">

  <div class="contentLeft">

    <h1>Hospitals &amp; Healthcare Systems</h1>
    <div class="lineRuleSolid"></div>

    <div id="left">

      <p>Each department and unit of a hospital produces abundant  volumes of pharmaceuticals wastes. Identifying which ones are hazardous from  non-hazardous can be quite complicated. With GICMD&rsquo;s convenient services, we can help make it easier  for you, your medical staff, and other hospital employees.<br>
</p>
      <p>Our intricate waste management guarantees that you:<img src="img/Pharmaceutical-Recall.jpg" alt="Pharmaceuticals returns and recall Canada" width="186" height="219" class="stock"></p>
      <ul>
        <li>Protect   the safety of your medical staff and employees</li>
        <li>Ensure the well-being of your patients and their  families</li>
        <li>Preserve the environment </li>
      </ul>
      <h3>Cost-effective Solutions</h3>
      <p>        Our extensive pharmaceuticals waste management include:</p>
      <ul>
        <li>Precise classification of hazardous  pharmaceuticals for segregation</li>
        <li>Premium waste disposal products (i.e. containers  and bins)</li>
        <li>Flexible collection or pick-up time</li>
        <li>Live tracking during transport</li>
        <li>Safe disposal</li>
      </ul>
      <p>You can also choose to customize a hassle-free waste  management program to suit your hospital&rsquo;s needs using our Hospital Integrated  Waste services. For hospitals and healthcare facilities most specially,  GICMD will conduct the following:</p>
      <ul>
        <li>Careful evaluation of the type of  pharmaceuticals generated by each department</li>
        <li>Determining the right location to set up specific  waste containers or bins</li>
      </ul>
      <h3>Sign-up for Compliance Training</h3>
      <p>        With all the hospital departments and units dispensing and  generating prescription drugs, it can lead to unsafe disposal. This would  ultimately lead to detrimental effects on the environment and to the general  public, including legal issues that might arise from negligence.</p>
      <p>Allow GICMD to help train your staff and employees the  proper ways to deal with pharmaceutical drugs and waste. We will provide them  the necessary information, standards, and compliant best practices in waste  management.</p>
      <h3> Our Expertise in Handling  Pharmaceuticals</h3>
      <p>        Let our experts handle your pharmaceutical materials, so  that your hospital&rsquo;s activities and operations do not get interrupted. Protect  everyone in your facility and keep your hospital&rsquo;s reputation secured with the  help of GICMD experts.</p>
      <p> GICMD employs the best, well-informed specialists that are  available for consultation at <strong><?= $to_phone; ?> </strong>(toll free). Contact us today for inquiries and more information about our  services.</p>
      </div>

    <br>

    <div class="clear"></div>

  </div>

  <?php include 'components/right.php'; ?>

  <?php include 'components/footer.php'; ?>
